export const BAG_TYPE_ALL = "ALL";
export const BAG_TYPE_BACKPACK = "BACKPACK";
export const BAG_TYPE_DUFFLE = "DUFFLE_BAG";
export const BAG_TYPE_TRAVEL = "TRAVEL_BAG";

export const PRODUCT_SORT_TYPE_RECOMMENDED = "RECOMMENDED";
export const PRODUCT_SORT_TYPE_PRICE_HIGH_TO_LOW = "PRICE_HIGH_TO_LOW";
export const PRODUCT_SORT_TYPE_PRICE_LOW_TO_HIGH = "PRICE_LOW_TO_HIGH";
export const PRODUCT_SORT_TYPE_NAME_ASC = "NAME_ASC";
export const PRODUCT_SORT_TYPE_NAME_DESC = "NAME_DESC";

export const QUANTITY_INCREMENT = "INCREMENT";
export const QUANTITY_REDUCTION = "REDUCTION";

export const SIDE_MENU_PRODUCTS = "PRODUCTS";
export const SIDE_MENU_LOGIN = "LOGIN";
export const SIDE_MENU_CART = "CART";
